version: '3'

services:
  systracker:
    image: ghcr.io/redwan002117/systracker:latest
    container_name: systracker-admin
    restart: unless-stopped
    ports:
      - "7777:7777"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=7777
